hard_tabs = false

max_width = 120

reorder_imports = true
reorder_modules = true

trailing_comma = "Vertical"

imports_granularity = "Crate"
struct_field_align_threshold = 20

indent_style = "Block"
fn_call_width = 80
